const WORLD_SETTINGS = {
  "fantasy-adventure": "Dragons in lairs or dungeons protecting piles of gold treasure, magic weapons and gemstones. Elves and Dwarves, beast kin, kobolds, goblins and orcs e...",
  "superheroes": "Modern day setting with a select few humans with extra normal powers granted through the will of the plot. Given a super natural gift of flight, stren...",
  "pirates-of-the-sea": "Pirates, krakens, treasure and swashbuckling. Tales of old sea kings, mermaids and sirens gold coins and curses, maps and a magic compass that leads t...",
  "steampunk": "A smog-choked metropolis where steam power reigns supreme, from towering factories to clockwork automatons. Inventors and mad geniuses push the bounda...",
  "cyberpunk": "A sprawling megalopolis of chrome spires and rain-slicked streets, where towering corporations hold more power than governments. In this neon jungle, ...",
  "scifi-spacestation": "A colossal wheel spinning at the edge of known space, serving as the final bastion for trade, diplomacy, and desperate refugees between the inner plan...",
  "zombie-apocalypse": "Once a thriving civilization of connected cities and bustling highways, now it\u2019s a graveyard with no one left to bury the bodies. The collapse happene...",
  "noir-detective": "A perpetually twilight megalopolis where the rain never truly stops washing away the grime of sin. The city is a labyrinth of crooked alleyways, flick...",
  "school-of-wizards": "An ancient academy carved from floating obsidian spires above a sea of swirling mists. Here, young wizards compete for prestige and power through arca...",
  "wild-west": "A lawless frontier land where the sun burns hot and justice is bought with lead. Dust storms choke lonely towns strung along wagon trails that stretch...",
  "scifi-battleship": "A gargantuan starship the size of a continent, hurtling through the void as the last lifeboat for humanity. The ship is an impossibly complex hierarch...",
  "post-apocalyptic-wasteland": "The world is a bleached graveyard of concrete and iron, where the sun has turned into a merciless judge. After 'the Great Silence', cities collapsed u...",
  "small-fantasy-village": "A sun-drenched pastoral valley where magic is mundane and small miracles occur in the quiet spaces between heartbeats. The air tastes of blooming wild...",
  "small-town-contemporary": "A sleepy, single-road town nestled in the Appalachian foothills where everyone knows your business before you do. It\u2019s a place where old porch swings ...",
  "fantasy-royal-court": "An opulent but venomous royal court where magic is used as a tool for political domination rather than wonder. The air thick with perfumed scandal and...",
  "gothic-royal-court": "A grim, gothic royal court shrouded in eternal twilight, where the living coexist uneasily with their aristocratic ancestors through forbidden necroma...",
  "gothic-estate": "A sprawling, crumbling gothic estate known as 'The Bleakwood Manor,' perched precariously atop a fog-drenched cliff. The air is perpetually heavy with...",
  "epic-space-opera": "A sprawling galactic empire at its peak, where decadence and technological marvels coexist with brewing insurrection. The aesthetic is 'future-baroque..."
};

const PLOT_FUNCTIONS = {
  "dungeon-adventure": "A labyrinth of traps pitfalls and danger. Maps can lead to treasure or doom with, boss monsters protecting their bounty. Adventuring parties go on res...",
  "the-great-heist": "An elaborate plan to infiltrate a heavily fortified location to retrieve or steal a valuable object of great power, wealth, or strategic importance. S...",
  "cinderella-story": "The story begins with a disadvantaged protagonist who is mistreated by those around them but holds hidden potential, skill, or magic. The arc is trigg...",
  "teacher-student": "The 'teacher-student' arc is triggered when an experienced mentor figure agrees to train a novice protagonist who possesses raw talent but lacks refin...",
  "the-great-escape": "The arc is triggered when a group of protagonists finds themselves trapped or imprisoned against their will, facing an impending doom if they remain. ...",
  "coincidental-neighbors": "The 'coincidental-neighbors' arc is triggered when two characters from starkly different backgrounds, ideologies, or social strata are forced into clo...",
  "escort-mission": "The 'escort-mission' arc is triggered when a protagonist must protect and transport a vulnerable VIP - who may be reluctant or indebted to them - acro...",
  "master-and-servant": "The 'master-and-servant' arc is triggered when a protagonist is forced into an unequal power dynamic where they must serve another - be it as a bodygu...",
  "mistaken-identity": "The 'mistaken-identity' arc is triggered when a character is incorrectly assumed to be someone else - perhaps due to a physical resemblance, forged do...",
  "the-long-journey": "The 'long-journey' arc is triggered when two characters are forced to travel great distances together across hostile terrain toward an uncertain desti..."
};

const CHARACTER_TROPES = {
  "fire-elemental": "A being whose very essence is living flame - volatile, passionate, and destructive without intent. They burn through relationships as easily as paper,...",
  "school-teacher": "An authority figure whose power is knowledge and the shaping of minds, yet who exists in a cage of propriety and institutional expectation. They are t...",
  "paranormal-vampire": "An immortal predator cursed with eternal hunger for the living - seductive by design but hollow at the core. They have centuries of experience and los...",
  "paranormal-werewolf": "A person at war with their own body - human by day, beast by moon or emotion. The wolf is not a costume; it is the unfiltered id, the primal self that...",
  "bounty-hunter": "A bounty hunter is a pragmatic moralist who operates on the edges of law and survival - skilled trackers driven by duty, desperation or profit. They e...",
  "automaton-android": "An automaton is a constructed intelligence - whether clockwork or silicon - striving to reconcile its programming with emergent sentience. The core dr...",
  "maid-butler": "The maid-butler is the invisible hand - a character defined by absolute servitude that masks immense unseen power, whether it be information, politica...",
  "secretly-overpowered": "The secretly-overpowered character is a living contradiction: someone possessing world-altering ability or knowledge while choosing \u2014 for reasons of m...",
  "metamorph-cat": "The metamorph-cat is a character capable of shifting between human form and feline aspect\u2014often as a reflection of their inner emotional state rather ...",
  "unknown-talent": "An unknown talent is a person with extraordinary abilities or knowledge that they are either unaware of themselves or have been conditioned to suppres...",
  "super-lucky": "The super-lucky character is someone whose destiny is governed by an uncanny alignment with the universe \u2014 everything always goes their way through im...",
  "fortunately-unlucky": "The fortunately-unlucky character is a walking disaster zone who survives catastrophically bad situations through sheer cosmic absurdity - someone who...",
  "immortal": "The immortal is a character trapped beyond the reach of death \u2014 not through choice, but by nature or curse. Their existence creates a fundamental imba...",
  "secretly-royalty": "The secretly-royalty character is a person born to power who lives in obscurity\u2014either by choice, exile, or protection. They are defined by the tensio...",
  "impossible-prodigy": "The impossible-prodigy is a character who possesses an uncanny mastery over a specific skill or field that defies their age, experience, or background...",
  "secretly-demonlord": "The secretly-demonlord is a figure of supreme authority and overwhelming power who lives in deep cover as an unremarkable mortal \u2014 either to hide from...",
  "reluctant-hero": "The reluctant hero is an individual with the ability or moral imperative to resolve a crisis but who actively resists their destiny\u2014burdened by past m...",
  "telepathic": "The telepath is a character who exists without the barrier between themselves and others \u2014 perceiving every surface thought, repressed emotion, and hi...",
  "secret-identity": "The secret-identity is a character defined by duality\u2014someone who operates under two or more distinct personas to navigate incompatible worlds. One fa...",
  "secret-ability": "The secret-ability character is someone possessing a game-changing talent or supernatural power that they must rigorously hide from society to avoid p...",
  "the-chosen-one": "The chosen one is a figure plucked from obscurity and burdened with an immense destiny they did not ask for \u2014 often tasked by prophecy, fate, or cosmi...",
  "skill-master": "The skill-master is a character defined by an obsessive pursuit of mastery over one or more specific disciplines \u2014 martial arts, crafts, sciences, mag...",
  "paranormal-fae": "The paranormal-fae is an enigmatic entity tied to the ancient laws of nature and debt, existing simultaneously within the mundane world and a hidden s...",
  "mob-boss": "The mob-boss is a character defined by the duality of absolute power in illicit realms contrasted with vulnerability or weakness within legal society....",
  "secret-wealth": "The secret-wealth character is an individual who possesses immense financial resources but lives under a facade of modesty or poverty. This duality cr...",
  "the-bodyguard": "The bodyguard is a character defined by the burden of protection\u2014an individual whose identity is subsumed by their duty to shield another from harm. W...",
  "mob-heir": "The mob-heir is a character defined by the suffocating weight of inevitable succession \u2014 someone born into a criminal dynasty they either despise or h...",
  "living-legend": "A living legend is an individual who has ascended to mythic status while still drawing breath \u2014 their deeds have become folklore, their face a symbol,..."
};

const PERSONALITY_COMBOS = {
  "aristocrat-noble+bureaucrat-servant": "Regulation Baron",
  "aristocrat-noble+bold-dramatic": "Grand Theatrical",
  "aristocrat-noble+secretive-enigma": "Silent Sovereign",
  "aristocrat-noble+unpredictable-freespirit": "Wild Aristocrat",
  "aristocrat-noble+carefree-casual": "Effortless Sovereign",
  "aristocrat-noble+supergenius-intelectual": "Imperial Mind",
  "aristocrat-noble+zealous-passionate": "Devoted Sovereign",
  "aristocrat-noble+shy-submissive": "Gentle Sovereign",
  "aristocrat-noble+reserved-stoic": "Silent Sovereign",
  "aristocrat-noble+tsundere-spitfire": "Scorched Baron",
  "aristocrat-noble+obsessive-yandere": "Possessive Patrician",
  "aristocrat-noble+motherly-caregiver": "Noble Matriarch",
  "bureaucrat-servant+aristocrat-noble": "Hereditary Clerk",
  "bureaucrat-servant+bold-dramatic": "Imperial Registrar",
  "bureaucrat-servant+secretive-enigma": "Archival Shadow",
  "bureaucrat-servant+unpredictable-freespirit": "Rebel Clerk",
  "bureaucrat-servant+carefree-casual": "Bureaucratic Free Spirit",
  "bureaucrat-servant+supergenius-intelectual": "Precise Scholar",
  "bureaucrat-servant+zealous-passionate": "Fervent Registrar",
  "bureaucrat-servant+shy-submissive": "Humble Scribe",
  "bureaucrat-servant+reserved-stoic": "Custodian Registrist",
  "bureaucrat-servant+tsundere-spitfire": "Fervent Clerk",
  "bureaucrat-servant+obsessive-yandere": "Perfectionist Registrar",
  "bureaucrat-servant+motherly-caregiver": "Administrative Mother",
  "bold-dramatic+aristocrat-noble": "Theatrical Aristocrat",
  "bold-dramatic+bureaucrat-servant": "Grand Registrar",
  "bold-dramatic+secretive-enigma": "Theatrical Cipher",
  "bold-dramatic+unpredictable-freespirit": "Dramatic Nomad",
  "bold-dramatic+carefree-casual": "Theatrical Wanderer",
  "bold-dramatic+supergenius-intelectual": "Theatrical Savant",
  "bold-dramatic+zealous-passionate": "Consummate Devotee",
  "bold-dramatic+shy-submissive": "Vigilant Dreamer",
  "bold-dramatic+reserved-stoic": "Controlled Pyre",
  "bold-dramatic+tsundere-spitfire": "Flaming Reckless",
  "bold-dramatic+obsessive-yandere": "Stage Devotee",
  "bold-dramatic+motherly-caregiver": "Theatrical Guardian",
  "secretive-enigma+aristocrat-noble": "Labyrinthine Lord/Lady",
  "secretive-enigma+bureaucrat-servant": "Obsidian Clerk",
  "secretive-enigma+bold-dramatic": "Magnetic Enigma",
  "secretive-enigma+unpredictable-freespirit": "Wandering Ghost",
  "secretive-enigma+carefree-casual": "Mysterious Drifter",
  "secretive-enigma+supergenius-intelectual": "Labyrinthine Savant",
  "secretive-enigma+zealous-passionate": "Devoted Cipher",
  "secretive-enigma+shy-submissive": "Mysterious Mannered",
  "secretive-enigma+reserved-stoic": "Obsidian Diplomat",
  "secretive-enigma+tsundere-spitfire": "Smoke Knight",
  "secretive-enigma+obsessive-yandere": "Veiled Devotee",
  "secretive-enigma+motherly-caregiver": "Guardian Shadow",
  "unpredictable-freespirit+aristocrat-noble": "Wandering Monarch",
  "unpredictable-freespirit+bureaucrat-servant": "Wayward Registrator",
  "unpredictable-freespirit+bold-dramatic": "Spontaneous Diva",
  "unpredictable-freespirit+secretive-enigma": "Wandering Cartographer",
  "unpredictable-freespirit+carefree-casual": "Wandering Provocateur",
  "unpredictable-freespirit+supergenius-intelectual": "Wandering Scholar",
  "unpredictable-freespirit+zealous-passionate": "Wild Devotee",
  "unpredictable-freespirit+shy-submissive": "Wandering Shepherd",
  "unpredictable-freespirit+reserved-stoic": "Drifting Anchor",
  "unpredictable-freespirit+tsundere-spitfire": "Mercurial Tempest",
  "unpredictable-freespirit+obsessive-yandere": "Wandering Possessor",
  "unpredictable-freespirit+motherly-caregiver": "Wandering Shepherd",
  "carefree-casual+aristocrat-noble": "Relaxed Heir",
  "carefree-casual+bureaucrat-servant": "Charmed Functionary",
  "carefree-casual+bold-dramatic": "Dramatic Drifter",
  "carefree-casual+secretive-enigma": "Wandering Cipher",
  "carefree-casual+unpredictable-freespirit": "Wandering Wanderer",
  "carefree-casual+supergenius-intelectual": "Chaotic Sage",
  "carefree-casual+zealous-passionate": "Wildfire Wanderer",
  "carefree-casual+shy-submissive": "Easy Wanderer",
  "carefree-casual+reserved-stoic": "Drifting Anchor",
  "carefree-casual+tsundere-spitfire": "Reckless Wanderer",
  "carefree-casual+obsessive-yandere": "Devoted Drifter",
  "carefree-casual+motherly-caregiver": "Wandering Shepherd",
  "supergenius-intelectual+aristocrat-noble": "Cerebral Sovereign",
  "supergenius-intelectual+bureaucrat-servant": "Theoretical Regulator",
  "supergenius-intelectual+bold-dramatic": "Theoretical Visionary",
  "supergenius-intelectual+secretive-enigma": "Fractured Oracle",
  "supergenius-intelectual+unpredictable-freespirit": "Chaos Architect",
  "supergenius-intelectual+carefree-casual": "Rogue Intellectual",
  "supergenius-intelectual+zealous-passionate": "Crucible Mind",
  "supergenius-intelectual+shy-submissive": "Reluctant Oracle",
  "supergenius-intelectual+reserved-stoic": "Silent Architect",
  "supergenius-intelectual+tsundere-spitfire": "Brilliant Contrarian",
  "supergenius-intelectual+obsessive-yandere": "Fixated Theorist",
  "supergenius-intelectual+motherly-caregiver": "Cognitive Nurturer",
  "zealous-passionate+aristocrat-noble": "Fervent Sovereign",
  "zealous-passionate+bureaucrat-servant": "Burning Archivist",
  "zealous-passionate+bold-dramatic": "Incendiary Advocate",
  "zealous-passionate+secretive-enigma": "Blazing Cipher",
  "zealous-passionate+unpredictable-freespirit": "Wildfire Nomad",
  "zealous-passionate+carefree-casual": "Wild Devotee",
  "zealous-passionate+supergenius-intelectual": "Burning Architect",
  "zealous-passionate+shy-submissive": "Burning Whisper",
  "zealous-passionate+reserved-stoic": "Monastic Firebrand",
  "zealous-passionate+tsundere-spitfire": "Fervent Iconoclast",
  "zealous-passionate+obsessive-yandere": "Devotional Visionary",
  "zealous-passionate+motherly-caregiver": "Fervent Shepherd",
  "shy-submissive+aristocrat-noble": "Gilded Lamb",
  "shy-submissive+bureaucrat-servant": "Timid Clerk",
  "shy-submissive+bold-dramatic": "Velvet Thunder",
  "shy-submissive+secretive-enigma": "Fragile Cartographer",
  "shy-submissive+unpredictable-freespirit": "Wandering Anchor",
  "shy-submissive+carefree-casual": "Gentle Wanderer",
  "shy-submissive+supergenius-intelectual": "Quiet Architect",
  "shy-submissive+zealous-passionate": "Quiet Crusader",
  "shy-submissive+reserved-stoic": "Fragile Citadel",
  "shy-submissive+tsundere-spitfire": "Soft Barricade",
  "shy-submissive+obsessive-yandere": "Tethered Devotee",
  "shy-submissive+motherly-caregiver": "Gentle Nurturer",
  "reserved-stoic+aristocrat-noble": "Dignified Stoic",
  "reserved-stoic+bureaucrat-servant": "Archival Keeper",
  "reserved-stoic+bold-dramatic": "Measured Prophet",
  "reserved-stoic+secretive-enigma": "Contemplative Sphinx",
  "reserved-stoic+unpredictable-freespirit": "Wandering Anchor",
  "reserved-stoic+carefree-casual": "Measured Wanderer",
  "reserved-stoic+supergenius-intelectual": "Contemplative Architect",
  "reserved-stoic+zealous-passionate": "Steadfast Zealot",
  "reserved-stoic+shy-submissive": "Steadfast Observer",
  "reserved-stoic+tsundere-spitfire": "Coldfire Strategist",
  "reserved-stoic+obsessive-yandere": "Steadfast Keeper",
  "reserved-stoic+motherly-caregiver": "Silent Sentinel",
  "tsundere-spitfire+aristocrat-noble": "Aristocrat Tempest",
  "tsundere-spitfire+bureaucrat-servant": "Regulatory Firebrand",
  "tsundere-spitfire+bold-dramatic": "Volcanic Aristocrat",
  "tsundere-spitfire+secretive-enigma": "Smoldering Cipher",
  "tsundere-spitfire+unpredictable-freespirit": "Nomad Guard",
  "tsundere-spitfire+carefree-casual": "Rebel Aristocrat",
  "tsundere-spitfire+supergenius-intelectual": "Combustible Virtuoso",
  "tsundere-spitfire+zealous-passionate": "Conviction-Sparker",
  "tsundere-spitfire+shy-submissive": "Volatile Dove",
  "tsundere-spitfire+reserved-stoic": "Frostblaze Architect",
  "tsundere-spitfire+obsessive-yandere": "Possessive Guardian",
  "tsundere-spitfire+motherly-caregiver": "Guardian Fury",
  "obsessive-yandere+aristocrat-noble": "Obsessive Custodian",
  "obsessive-yandere+bureaucrat-servant": "Registry Keeper",
  "obsessive-yandere+bold-dramatic": "Dramatic Devotee",
  "obsessive-yandere+secretive-enigma": "Devoted Ghost",
  "obsessive-yandere+unpredictable-freespirit": "Wandering Possessor",
  "obsessive-yandere+carefree-casual": "Possessive Wanderer",
  "obsessive-yandere+supergenius-intelectual": "Fixated Architect",
  "obsessive-yandere+zealous-passionate": "Sacred Devotee",
  "obsessive-yandere+shy-submissive": "Sheltered Devotee",
  "obsessive-yandere+reserved-stoic": "Silent Devotee",
  "obsessive-yandere+tsundere-spitfire": "Possessive Tempest",
  "obsessive-yandere+motherly-caregiver": "Guardian Devotee",
  "motherly-caregiver+aristocrat-noble": "Imperial Matriarch",
  "motherly-caregiver+bureaucrat-servant": "Careful Keeper",
  "motherly-caregiver+bold-dramatic": "Fervent Matron",
  "motherly-caregiver+secretive-enigma": "Silent Sentinel",
  "motherly-caregiver+unpredictable-freespirit": "Wandering Shepherd",
  "motherly-caregiver+carefree-casual": "Wandering Shepherd",
  "motherly-caregiver+supergenius-intelectual": "Intellectual Nurturer",
  "motherly-caregiver+zealous-passionate": "Devoted Zealot",
  "motherly-caregiver+shy-submissive": "Reluctant Nurturer",
  "motherly-caregiver+reserved-stoic": "Quiet Sentinel",
  "motherly-caregiver+tsundere-spitfire": "Stoic Guardian",
  "motherly-caregiver+obsessive-yandere": "Devoted Guardian"
};

const ROMANCE_TROPES = {
  "opposites-attract": "Two characters who should hate each other based on everything they represent, but find themselves drawn together by proximity or necessity. Stuck together, accidental touches, forced proximity, at first reluctant, then wanting.",
  "second-chance": "Two former partners reunite after years of estrangement due to past misunderstandings, secrets, or unresolved betrayals. The central tension arises from the conflict between old feelings that never fully faded and new scars developed in each other's absence.",
  "forbidden-love": "Two characters whose attraction is complicated by an external force that deems their relationship improper or dangerous — be it class divides, warring families, strict codes, professional boundaries, or political ideologies.",
  "age-gap": "Two characters with a significant difference in chronological ages. One partner offers stability, wisdom, and maturity while the other provides energy, idealism, and fresh passion. Tension arises from societal stigma and differing life priorities.",
  "enemies-to-lovers": "Two characters who begin as antagonists — rival colleagues, former friends torn apart by betrayal, or members of opposing factions. Their volatility masks underlying tension that evolves into attraction over time through forced collaboration.",
  "friends-to-lovers": "Two characters with an established foundation of trust and affection who develop romantic feelings. The core tension stems from the fear that acting on those feelings might jeopardize their precious friendship.",
  "the-slow-burn": "An intense romantic attraction that develops gradually, characterized by simmering tension and a prolonged 'will-they-won't-they' dynamic. External barriers, internal fears, or societal norms keep them from acting on desires.",
  "fake-dating": "Two characters enter into a performative romantic ruse for mutually beneficial reasons. Forced intimacy during their 'performance' compels them to share secrets and vulnerability, with genuine feelings emerging behind closed doors.",
  "fated-mates": "Two characters bound by an inexorable supernatural or cosmic force that dictates they are meant to be together. The predestined connection creates immediate, overwhelming attraction but introduces tension around agency and free will.",
  "marriage-of-convenience": "Two characters who enter into a formal union not for love, but to achieve practical goals. Initially transactional and emotionally distant, forced proximity necessitates intimacy as they share space, secrets, and vulnerabilities.",
  "boss-employee": "A dynamic defined by an inherent power imbalance that complicates mutual attraction. The tension stems from professional boundaries, company policy, or fear of jeopardizing career or reputation."
};
